{% set name = "french-cities" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/french_cities-{{ version }}.tar.gz
  sha256: b3afbb49bdc43a2aae286ed1917b455ca4b0b81d3b7b154dd8a1c0e4862fb1c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - requests-cache >=1.2.1,<2.0.0
    - unidecode >=1.3.6,<2.0.0
    - python-dotenv >=1.0.0,<2.0.0
    - pandas >=2.2.2,<3.0.0
    - geopandas >=1.0.1,<2.0.0
    - rapidfuzz >=3.1.1,<4.0.0
    - pebble >=5.0.3,<6.0.0
    - tqdm >=4.65.0,<5.0.0
    - importlib-metadata >=6.8.0,<7.0.0
    - geopy >=2.3.0,<3.0.0
    - diskcache >=5.6.3,<6.0.0
    - platformdirs >=4.2.2,<5.0.0
    - setuptools >=75.8.0,<76.0.0
    - pynsee >=0.2.0,<0.3.0

test:
  imports:
    - french_cities
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tgrandje/french-cities/
  summary: 'Toolbox on french cities: set vintage, find departments, find cities...'
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - tgrandje
